import { auth } from "@/auth";
import { db } from "@/lib/db/drizzle";
import { user } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth.api.getSession({ headers: await headers() });

    if (!session?.user?.id) {
        redirect("/")
    }

    const ConnectedUser = await db.select().from(user).where(eq(user.id, session.user.id));
    if (ConnectedUser[0].role !== "admin"){
      redirect("/")
    }
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
