import type { Metadata } from "next";
import "./globals.css";
import { Connection } from "./components/connectionForms/Connection";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <div className="fixed">
            <Connection />
          </div>
          <div id="layoutTitle" className="flex justify-center">
            <Link href="/">
              <h2 className="">Collab'</h2>
            </Link>
          </div>
        {children}
      </body>
    </html>
  );
}
